"use client"
import { useState, useEffect } from 'react'
import { documentsApi } from '@/lib/api'

export default function DocumentsPage() {
  const [docs, setDocs] = useState([])
  const [templates, setTemplates] = useState([])
  const [loading, setLoading] = useState(true)
  const [selected, setSelected] = useState(null)

  useEffect(() => { load() }, [])
  const load = async () => {
    try {
      const [d, t] = await Promise.all([
        documentsApi.list().catch(()=>[]),
        documentsApi.templates().catch(()=>[]),
      ])
      setDocs(d||[]); setTemplates(t||[])
    } catch(e) { console.error(e) }
    finally { setLoading(false) }
  }

  if (loading) return <div style={{padding:40,color:'var(--white-3)'}}>Loading documents...</div>

  const docTypes = [
    {icon:'📋',name:'AGM Minutes'},{icon:'⚖',name:'Board Resolution'},{icon:'🔄',name:'Share Transfer'},
    {icon:'📊',name:'Compliance Report'},{icon:'⚑',name:'Rescue Roadmap'},{icon:'💼',name:'Engagement Letter'},
  ]

  return (
    <div style={{padding:24}}>
      <div className="font-garamond" style={{fontSize:22,color:'var(--nlc-white)',marginBottom:6}}>Document Engine</div>
      <div style={{fontSize:12,color:'var(--white-3)',marginBottom:18}}>AI-assisted drafting. All outputs require review.</div>
      <div style={{display:'flex',alignItems:'center',gap:10,marginBottom:18,padding:'10px 14px',background:'var(--green-bg)',borderRadius:8,border:'1px solid var(--gold-line)'}}>
        <span style={{color:'var(--green)',fontSize:8}}>●</span>
        <span style={{fontSize:11.5,color:'var(--green)',fontWeight:600}}>AI Drafting Active</span>
        <span style={{fontSize:11,color:'var(--text2)'}}>— outputs cannot be auto-sent to clients</span>
      </div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}>
        <div className="nlc-card">
          <div className="sec-lbl">Select Document Type</div>
          {docTypes.map(d => (
            <button key={d.name} onClick={()=>setSelected(d.name)} className="nlc-btn-ghost" style={{width:'100%',padding:'10px 14px',textAlign:'left',marginBottom:6,fontSize:12,background:selected===d.name?'var(--navy)':'transparent',color:selected===d.name?'var(--gold)':'var(--navy)',borderColor:selected===d.name?'var(--navy)':'var(--border2)'}}>
              {d.icon} {d.name}
            </button>
          ))}
        </div>
        <div>
          <div className="nlc-card" style={{marginBottom:14}}>
            <div className="sec-lbl">Document Parameters</div>
            {[['Company Name',''],['Registration No.',''],['Financial Year',''],['Date','']].map(([l,v])=>(
              <div key={l} style={{marginBottom:14}}>
                <label className="f-label">{l}</label>
                <input className="nlc-input" placeholder={v||'Enter...'} />
              </div>
            ))}
            <button className="nlc-btn-primary" style={{fontWeight:700,padding:'10px 20px'}} onClick={()=>alert('AI generation requires backend setup')}>Generate AI Draft</button>
          </div>
          {selected && (
            <div className="nlc-card" style={{borderLeft:'4px solid var(--gold)'}}>
              <div style={{display:'flex',justifyContent:'space-between',marginBottom:14}}>
                <div className="sec-lbl" style={{margin:0,border:'none',padding:0}}>Preview — {selected}</div>
                <span className="badge badge-yellow">DRAFT</span>
              </div>
              <textarea style={{width:'100%',padding:14,border:'1px solid var(--border)',borderRadius:7,fontSize:11.5,fontFamily:"'JetBrains Mono',monospace",lineHeight:1.7,resize:'vertical',boxSizing:'border-box',background:'var(--surface)',outline:'none'}} rows={10} placeholder="AI-generated document will appear here..." defaultValue={`[SELECTED: ${selected}]\n\nThis document will be generated by the AI engine.\n\nAll AI-generated documents require human review\nbefore filing with RJSC.\n\nDRAFT — NOT FOR FILING`} />
              <div style={{display:'flex',gap:8,marginTop:14}}>
                <button className="nlc-btn-primary">Export PDF</button>
                <button className="nlc-btn-ghost">Export .docx</button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
