"use client"

export default function LegalDisclaimer({ compact = false }: { compact?: boolean }) {
  if (compact) {
    return (
      <p style={{ fontSize: 10, color: "var(--text3)", lineHeight: 1.45, margin: "8px 0 0" }}>
        Decision-support tool only. Not a substitute for qualified legal advice or official RJSC determinations.
      </p>
    )
  }
  return (
    <div
      style={{
        marginTop: 16,
        padding: "10px 14px",
        borderRadius: 8,
        border: "1px solid var(--border)",
        background: "var(--surface2, #f8f9fb)",
        fontSize: 11,
        color: "var(--text3)",
        lineHeight: 1.5,
      }}
    >
      <strong style={{ color: "var(--text2)" }}>Disclaimer: </strong>
      Neum Lex Counsel scores and flags are compliance intelligence aids generated by a deterministic rule engine.
      They do not constitute legal advice and are not a substitute for advice from a qualified Bangladesh company-law
      practitioner or for any determination by the Registrar of Joint Stock Companies and Firms (RJSC).
    </div>
  )
}
